### ISSUE TITLE
Publish app on flathub

### ISSUE THREAD

**Issue by adityashah1212** [mariospr/chromium-browser-xdg-app#1]
Publish this app at [Flathub](https://github.com/flathub/flathub).

**Comment by mariospr** [comment]
Unfortunately this is not possible: Chromium uses its own sandboxing mechanism based on a setuid binary that can't work at all inside bubblewrap as that component basically drops all the permissions and capabilities required to acquire new privileges inside the sandbox, rendering the setuid binary a normaly binary, and therefore preventing chromium from working.

This means that, unless Chromium makes the required changes to allow it running inside a different "external" sandbox such as flatpak's (and there's a [ticket opened for that already](https://bugs.chromium.org/p/chromium/issues/detail?id=622061&q=flatpak&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified), the only ways I can think of that you could run chromium as a flatpak are:
  1. Run chromium with `--no-sandbox`, to disable its own sandbox.
  2. Run chromium right off the directory flatpak deploys it into, either directly or via a wrapper script

The problem with (1) is that it's very insecure as it defeats one of the main points of chromium, which will complain loudly with a banner when starting up. This is how this experiment worked so far and, while it's nice to experiment with, it's not good enough for releasing it in flathub, and the main reason I'm closing this issue.

The problem with (2) is that doing so defeats partially the point of flatpak, which would be only used as a delivery mechanism. This is a useful workaround (yet a workaround after all, let's be clear on that), though, in controlled environments like Endless, where we decided to implement a [wrapper script that would do precisely that](https://github.com/endlessm/eos-browser-tools/blob/master/chrome-helper/eos-google-chrome.py), so that we could give our users the chance to install Chrome from the app store as any other flatpak apps, even though flatpak in this case would only be used to deliver the application, that would run outside the flatpak's sandbox thanks to this wrapper script provided by the OS.

Either way, as you can probably understand by know, this "chromium flatpak" thing is not yet in a state that can be proposed to be integrated in flatpak. My initial plan was to keep working on this for a while to help Chromium get to a state where it could somehow work with flatpak nicely, but other tasks got in the middle and never got to do it, and so this kept here as what it is: an experiment, nothing else.

Sorry if this caused any trouble or misunderstanding. FWIW, I've just updated the README to be clear on that the `--no-sandbox` parameter needs to be passed for this to work.

Last, note that this experiment was done against Endless's version of chromium-browser at the time I worked on this (more than a year ago) so it's very likely that further changes needed to be done for this to work as it is with a newer chromium from upstream, which is something I don't have time for at the moment either, unfortunately.

**Comment by valentindavid** [comment]
My understanding is that Chrome uses the setuid sandbox only for older kernel (<3.8). I do not t think you can run flatpak on such an old kernel.

See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_sandboxing.md

**Comment by mariospr** [comment]
Oh! That's very interesting, thanks for sharing @valentindavid. I didn't know about this at the time I did this experiment (more than 1 year ago) and unfortunately I never got the time to continue investigating it, but this indeed might change things.

For what it's worth I checked chrome://sandbox in my linux machine and indeed it's **not* using the SUID.

Two sore points yet, though, are the fact that chromium still uses user namespaces internally and seccomp rules to sandbox its processes (and I don't think that's something you can do once you're inside a flatpak sandbox) and that this experiment has been done with a downstream copy of chromium more than 1 year ago (so even if it worked it would need more work), so I still don't see this getting into flathub anytime soon.

That said, don't get me wrong: I'd very much welcome having an official flatpak of chromium/chrome available, but there's still work that needs to be done in the chromium side before we can get to that point, for which I believe https://bugs.chromium.org/p/chromium/issues/detail?id=622061 is a better place to track that kind of effort.
